### ISSUE TITLE
TODO: Add favourites

### ISSUE THREAD

**Issue by fransschreuder** [fransschreuder/libosmscout#1]

**Comment by Borim7** [comment]
OSM Scout is very helpful, but searching for the same places again and again is annoying. I hope this feature is coming soon.

**Comment by fransschreuder** [comment]
Sure, it would also be nice if I got help from people developing this free app. I don't have a lot of time.

**Comment by Borim7** [comment]
Maybe later, I have to learn how to handle Ubuntu Apps first ;)

**Comment by fransschreuder** [comment]
Just uploaded a new version with favourites and home location. (may need some shaping though)
