### ISSUE TITLE
Doesn't work at all on my Bq after reinstallation

### ISSUE THREAD

**Issue by adridevlyon** [fransschreuder/libosmscout#11]
Hello,

I installed the app on my Bq E4.5 and then removed it and removed manually the .local/share/osmscout.fransschreuder folder containing the map I downloaded.
Now I installed again the app and when I launch it nothing happens : it is just like freezed (like on the attached screen), I cannot swipe from the bottom-edge nor search anything

How can I solve this problem ?
Thanks in advance,

AdricoM

![screenshot20150622_003242282](https://cloud.githubusercontent.com/assets/12992234/8273623/64ddf732-1876-11e5-9082-f9d66e2ba9c0.png)

**Comment by fransschreuder** [comment]
Hello, I tried to reproduce with all different versions, but it doesn't lock here. Did you have this problem once, or all the time?

**Comment by adridevlyon** [comment]
I tried uninstalling and installing again 3 or 4 times with the same problem
Could it be that the app "remembers" having been installed on my device and doesn't do any initializing/configuration job when installing again ?

**Comment by fransschreuder** [comment]
Have you tried rebooting as well?

**Comment by adridevlyon** [comment]
Yes, I tried different things :
- reboot, uninstall, reinstall
- uninstall, reinstall, reboot
- uninstall, reboot, reinstall

And in any way the same result

**Comment by adridevlyon** [comment]
Otherwise, is there another way for me to install it on my phone (I mean, other than from the store) ?
If it helps, I use ubuntu desktop too. I never compiled sources to my phone but I could if you explained me how

**Comment by fransschreuder** [comment]
Sure, if you go to https://open.uappexplorer.com/ you get the full-featured version without SD-Card restrictions, and can keep the screen on.
I don't know why your app hangs though, you should send me terminal output before I can say anything.

**Comment by fransschreuder** [comment]
can you get me the contents of:
/home/phablet/.cache/upstart/application-click-osmscout.fransschreuder_OSMScout_0.4.0.log*?

**Comment by adridevlyon** [comment]
I can't put them into this issue cause it seems to accept only png/gif/jpg.

Here you have the content of the .log file
https://framabin.org/?c345ac1ce8e02062#LzyvfKIq/4+3//DCEjCYFBaf+K1LdsYhg0VUk1zD/EM=
and the content of the 3 archived logs :
https://framabin.org/?69cdf4e1f0584249#vr9eAXJNR9jCwFyGWJHuEyyZdBvGOxqHwjq+FQSKaRo=
https://framabin.org/?984e9329425e6392#rXT/UvN+PzqHUC3xzzJV5KSkQWhtATFDkm1Ei7bIZWc=
https://framabin.org/?7a3d2efd8cf601f8#czl89u/pz14KQpwounIgLzFhsb6zMyOcuEnCM1SxXZw=

To help, I saw that no /home/phablet/.local/share/osmscout.fransschreuder folder have been recreated after I reinstalled the app, is it normal ?

**Comment by adridevlyon** [comment]
the version present on https://open.uappexplorer.com/ enables to store maps on sd card, is that right ? What is the difference with the screen part ? is it impossible to have the screen on via the official store ? Why are there those differences actually ? Are these limitations imposed to be on the official store ?

**Comment by fransschreuder** [comment]
1) Yes
2) Apparmor rules
3) Yes
4) Apparmor rules
5) Yes

The code is exactly the same, only in the official Ubuntu store, SD Card access and other special apparmor rules (eg to keep the screen on) are not allowed. Complaints are already all over the ubuntu-phone mailing list, but it doesn't matter if you complain as well. Address it to the right people though, it's beyond my control

**Comment by fransschreuder** [comment]
It's normal that the osmscout.fransschreuder folder is not created, it will only be created when downloading maps.
You said that the error only occurred after you deleted osmscout.fransschreuder. What happens if you crecreate the folder manually?

**Comment by adridevlyon** [comment]
I tried creating the folder again via the terminal, as normal user and with sudo : in both cases it didn't work better, and the log would be the same

Looking at the logs, I saw this line :
"Caught runtime exception from mediascanner: unable to open database file"
would it be a database file that could have been deleted and not created at the reinstallation ?

**Comment by adridevlyon** [comment]
And I installed it from open app store with the same result (only one line more logged when looking into the SD card Maps folder, actually existing but not recognized as valid either)

**Comment by fransschreuder** [comment]
The Caught runtime exception from mediascanner is normal when no map is present, I get it too.
Does the map folder also contain actual maps? If Maps is empty it will give a message that it is not valid. (valid for download though)

**Comment by adridevlyon** [comment]
it is empty actually
and looking into the code I understand why the "Could not find valid map dir" error : I only have an empty Maps folder, so no subfolder containing standard.oss file

What I don't understand is why I can't swipe in the app nor do anything

**Comment by fransschreuder** [comment]
I also don't understand it, your log output looks perfect

**Comment by AdricoM** [comment]
I am downloading a map to see if having a map in my Maps folder would help
I'll let you know when I would see the result

**Comment by adridevlyon** [comment]
I finally decided to reinitialize my device and after reinstalling the app, everything works

Thank you for your time !

**Comment by fransschreuder** [comment]
Ok, good! how did you reinitialize?

**Comment by adridevlyon** [comment]
in "System settings", "Reinitializing the device", with the option "Erase and reinitialize all" (Not sure of the labels, my phone is in French)
