### ISSUE TITLE
Have the choice to download a map into the SD card or into the local folder

### ISSUE THREAD

**Issue by adridevlyon** [fransschreuder/libosmscout#12]
This is only for the app with no restriction to access SD card (currently not the official version but the version on https://open.uappexplorer.com/)

If would be great if when downloading a map from the app there were the possibility to choose whether to download it into the SD card or into the local folder

**Comment by fransschreuder** [comment]
ok, fair enough... will be solved in next release

**Comment by adridevlyon** [comment]
thanks :)

**Comment by fransschreuder** [comment]
for now, you can eject or remove your SD card and it will automatically store in $HOME/Documents/Maps

**Comment by AdricoM** [comment]
the idea was to download it into my sd card ;)

**Comment by fransschreuder** [comment]
Done... added a settings dialog in which you can choose the download folder

**Comment by Theodin** [comment]
Nice. Thanks.
