### ISSUE TITLE
Street names are to small to read

### ISSUE THREAD

**Issue by ronnietucker** [fransschreuder/libosmscout#14]
Not sure about the BQ 4.5, or 5, but on the Meizu MX4 the text on all the street names is waaaay too small to read, even when zoomed in. See attached screenshot.

Thanks!
Ronnie

![screenshot20150623_165914241](https://cloud.githubusercontent.com/assets/10391379/8310950/0c97103a-19cb-11e5-83ed-bb2166683e55.jpg)

**Comment by fransschreuder** [comment]
I will check this, BQ E4.5 has a lower resolution, probably should take resolution into account.

**Comment by ronnietucker** [comment]
Cool. Thanks.

Not sure if it's the same thing with the BQ E5.

**Comment by Theodin** [comment]
I observed the same, but didnt find the time to see if this can be fixed by tinkering with the standard.oss file.

**Comment by fransschreuder** [comment]
No, you don't need to mess with standard.oss, I will add a parameter in DBThread.cpp (line 346) to set the fontSize, depending on dpi. To be fixed in next release

**Comment by fransschreuder** [comment]
Could you try to run 0.4.1? It should have a bigger font, depending on dpi

**Comment by Theodin** [comment]
Much better. Thanks!

**Comment by ronnietucker** [comment]
Still teeny tiny writing on the MX4 I'm afraid.

It does look readable on the screenshots (attached) but on the phone it's tiny.

Also: any chance of being able to split the Great Britain map? The large file really slows the app down.

![screenshot20150624_122932803](https://cloud.githubusercontent.com/assets/10391379/8335050/2b8a047a-1a93-11e5-95aa-90944b87a5d2.png)
![screenshot20150624_122945772](https://cloud.githubusercontent.com/assets/10391379/8335051/2b959aec-1a93-11e5-892e-4d8117030365.png)
![screenshot20150624_122952670](https://cloud.githubusercontent.com/assets/10391379/8335052/2b9a2bca-1a93-11e5-9ed2-99210ebd3c40.png)

**Comment by fransschreuder** [comment]
Ronnietucker: do you have ubuntu-sdk installed? If so, would you be able to download the sourcecode, play a little bit with the lines 347 "fs*=(dpi/50); //for 100DPI, multiply by 1.5" in this file?
https://github.com/fransschreuder/OSMScout-ubuntu/blob/master/OSMScout/OSMScout/src/DBThread.cpp

So could you tell me which number gives you an acceptable font size on the Meizu?

**Comment by fransschreuder** [comment]
oh, and I am currently converting england, wales and scotland...

**Comment by ronnietucker** [comment]
Sorry, I've not got the Ubuntu-SDK installed. From what I can tell the screen is 418ppi (if that's any help): http://www.phonearena.com/phones/Meizu-MX4_id8884

Awesome. Having only one region should speed things up I hope.

Thanks!  :)

**Comment by fransschreuder** [comment]
You could be of great help if you installed it and try

**Comment by ronnietucker** [comment]
I can give it a try. What do I need to do?

**Comment by fransschreuder** [comment]
First install Ubuntu-SDK
https://developer.ubuntu.com/en/start/ubuntu-sdk/installing-the-sdk/
In Ubuntu-SDK install the click target "15.04" for armhf, this will take some time
get yourself a copy of OSMScout
sudo apt-get install git
git clone https://github.com/fransschreuder/OSMScout-ubuntu.git

in Ubuntu SDK, open OSMScout-ubuntu/OSMScout/OSMScout.pro
there you can edit the lines I mentioned before

**Comment by ronnietucker** [comment]
OK, I'll give that a go.

And how do I try the app on the phone?

**Comment by fransschreuder** [comment]
Just connect the usb cable and press the green "play" button.

**Comment by fransschreuder** [comment]
oh, on the phone you will need to enable developer mode (settings => about this phone => developer mode

**Comment by ronnietucker** [comment]
Uh oh. This is where I could have problems. My Kubuntu 15.05 doesn't detect my phone.

I'll keep at it though.

**Comment by fransschreuder** [comment]
even if it doesn't see the files, there is a good chance that the adb connection which ubuntu-sdk uses does work

**Comment by fransschreuder** [comment]
if it doesn't you can also build the click package, transfer it to your phone somehow and from the terminal app run:
pkcon install-local --allow-untrusted osmscout.fransschreuder-<version>.click

**Comment by ronnietucker** [comment]
Worst case scenario is that I transfer it over using Dropbox.

**Comment by ronnietucker** [comment]
Please hold the line.

I think it's downloading the whole Internet.   :D

**Comment by fransschreuder** [comment]
haha, no it's just the northern part of the internet :)

**Comment by ronnietucker** [comment]
I've upped the dpi/xx to 400 and waiting to see if it'll finish building OK.

Will report back with findings...

**Comment by ronnietucker** [comment]
I've no idea what I'm doing, but when I click the green play button and I get:
![sdk](https://cloud.githubusercontent.com/assets/10391379/8339130/310ea30a-1aad-11e5-9d88-862cb4d1185d.jpg)

**Comment by fransschreuder** [comment]
you should change the dpi/50 to a smaller number in order to get bigger fonts. It appears like it doesn't see your phone yet, but if you go to the "publish" tab, you can build a click package and install it in another way

**Comment by ronnietucker** [comment]
Got the .click but when I try and install it (via terminal) I get:

Fatal error: [path and file] failed to install.
Cannot install [path and file] signature verification error: debug: findMember: archive appears to be corrupt, fmag incorrect.

**Comment by fransschreuder** [comment]
hmmm I don't know. What happens if you unlock your phone, connect the usb cable and set it to developer mode? you should at a certain point get a green dot on the ubuntu logo in the SDK, where it is red now.

**Comment by ronnietucker** [comment]
Nope. My Kubuntu 15.04 won't pick up my MX4 for some reason.   :(

**Comment by fransschreuder** [comment]
Did you give up?

**Comment by ronnietucker** [comment]
I'm clueless about developing, so I've no idea what to do next.   :/

**Comment by fransschreuder** [comment]
Have you tried all usb ports? A colleague of mine had the issue that not all usb ports of his computer could connect to his phone

**Comment by fransschreuder** [comment]
it also looks like the click package got corrupted somehow during the transfer. You could try to put it on a micro SD card

**Comment by fransschreuder** [comment]
I can't fix your bug if you can't test it.

**Comment by ronnietucker** [comment]
Tried all USB ports. It seems to be a problem with kio-mtp in KDE Plasma 5.   :(

I'd love to test/fix it, but I have no idea how to use Ubuntu SDK.

Could you send over a couple of different click files, each with different ppi values, and I'll let you know which one(s) look best?

**Comment by fransschreuder** [comment]
sudo apt-get install ubuntu-desktop
Then log out and you will get Unity, that may help if it's KDE related

**Comment by ronnietucker** [comment]
No thanks. I'll stick with KDE.

I'll never use Ubuntu SDK as I don't know how to code.  :(

**Comment by fransschreuder** [comment]
There's no need to code, just to change this number in order to get this bug fixed.
But if you don't feel like investing more effort this bug will just stay until somebody else can test. I don't have the Meizu phone so I have to rely on somebody who does.

**Comment by fransschreuder** [comment]
I may want to create a settings dialog, I will include a slider for the font size, maybe you can play a little with that...

**Comment by ronnietucker** [comment]
Sure. I'm totally OK with testing stuff on the Meizu, but I'm hopeless with the SDK.  :(

**Comment by fransschreuder** [comment]
You were almost there... If the phone connection works you just have to hit the green play button

**Comment by Markcortbass** [comment]
Can you see your phonefolders with a filemanager in (K)ubuntu? So then you know your phone is connected. If not, try the filemanager "PCMANFM".
Make sure you have enabled developer mode on your phone.

Keep the screen of your phone on, and use these commands to install the .click package:

cd /home/PATH_OF_FOLDER
click build .
adb push PACKAGE_NAME.click /home/phablet/Downloads/
adb shell
cd Downloads
pkcon install-local --allow-untrusted PACKAGE_NAME.click

**Comment by fransschreuder** [comment]
I have just uploaded a new version, this version has a settings dialog in which you can set the font size

**Comment by ronnietucker** [comment]
Perfect. Thanks!
