### ISSUE TITLE
Should have a default world map package pre installed

### ISSUE THREAD

**Issue by cm-t** [fransschreuder/libosmscout#15]
OsmScout should have a worldwild map (no detailled zoom) pre installed, so at least user will be able to check the app (another enhancement could be detecting no map is installed, and not showing only a text but a button or asking to swipe from bottom to add map. Both of those enhancement should be there imho)

**Comment by fransschreuder** [comment]
At the moment I don't have tools to create less-detailed maps, so this is impossible for now. Maybe in the far future.
