### ISSUE TITLE
Muting the phone doesnt mute OSMScout

### ISSUE THREAD

**Issue by Theodin** [fransschreuder/libosmscout#16]
Yesterday, I used the navigation feature for the first time and was greeted by a lovely lady guiding my way speaking british english. Nice!
But at some point I muted my phone and the lady kept giving me direction.
Please mute the app when the phone is in silent mode.

**Comment by fransschreuder** [comment]
I think this is a general Ubuntu issue, not only OSMScout suffers from this problem but all other apps that use audio are behaving the same way. 
If you can point me to a way how to detect silent mode, it would be appreciated

**Comment by Theodin** [comment]
I'll see what I can find out and get back to you.

**Comment by fransschreuder** [comment]
I have created a thread on https://lists.launchpad.net/ubuntu-phone/msg13667.html
There seems to be a bug in the system...

**Comment by fransschreuder** [comment]
A bug has been filed here:
https://bugs.launchpad.net/ubuntu/+source/qtubuntu-media/+bug/1468793

**Comment by Theodin** [comment]
Thanks for escalating it to the proper channels.
