### ISSUE TITLE
Navigation freeze

### ISSUE THREAD

**Issue by Theodin** [fransschreuder/libosmscout#19]
In the last days, OSMScout froze (even the speed I was driving at didnt update any more). I think it could be related to the zoomlevel. I will post my logs later in the hope thy help.

**Comment by fransschreuder** [comment]
I have seen once that there is a file ~/.config/osmscout.fransschreuder/osmscout.conf.lock
Removing this file solved the issue
If this problem occurs, the app is not controllable at all and may also crash.

**Comment by fransschreuder** [comment]
If it's just your gps position that doesn't update anymore (and the speed) it may very well related to the GPS implementation in the Ubuntu system. Try turning off your wifi while navigating

**Comment by Theodin** [comment]
The whole app was unresponsive. Next time this happens, I will check with sensor status, if the gps is updating or not.

**Comment by fransschreuder** [comment]
Ok, it's a known issue of the Ubuntu Phone that GPS and Wifi are no friends, GPS will need a lot of improvement, hopefully better in OTA5

**Comment by fransschreuder** [comment]
please reopen if still applicable
