### ISSUE TITLE
Navigation information text to small

### ISSUE THREAD

**Issue by Markcortbass** [fransschreuder/libosmscout#21]
The navigation information text to small to read while driving
![text_small](https://cloud.githubusercontent.com/assets/6825753/8454574/aeebbabe-1ffe-11e5-926d-2510694e7ffb.png)

**Comment by fransschreuder** [comment]
Ok, fair enough.. I can make it bigger

**Comment by Markcortbass** [comment]
That would be great! ;) Thank you very much for this amazing navigation app and your support!

**Comment by fransschreuder** [comment]
I made them bigger (committed but not in the store yet)

**Comment by Markcortbass** [comment]
I confirm this as solved :)
![screenshot20150703_112139966](https://cloud.githubusercontent.com/assets/6825753/8497522/479fb870-217e-11e5-9063-09a793674448.png)
