### ISSUE TITLE
Navigation road indication is not visible enough

### ISSUE THREAD

**Issue by Markcortbass** [fransschreuder/libosmscout#22]
The navigation road indication is not visible enough.
The red line should be brighter red and wider.
![screenshot20150625_164029742](https://cloud.githubusercontent.com/assets/6825753/8454649/841b69c8-1fff-11e5-95cb-fab77522a442.png)

**Comment by fransschreuder** [comment]
Let me see what I can do to make it bigger.

**Comment by fransschreuder** [comment]
I have made it less transparent and twice as big. The changes are made in standard.oss. You either have to download standard.oss from http://schreuderelectronics.com/osm or download the whole map from the app.

**Comment by Markcortbass** [comment]
Thank you very much! It's way more visible now.
![screenshot20150701_223541219](https://cloud.githubusercontent.com/assets/6825753/8464716/9300b1ce-2044-11e5-8b20-4de3ab904cd0.png)
