### ISSUE TITLE
Resume music after navigation voice guidance

### ISSUE THREAD

**Issue by Markcortbass** [fransschreuder/libosmscout#23]
The music stops when the voice navigation guidance is active. The music isn't resumed after that.

**Comment by fransschreuder** [comment]
This is an ubuntu issue, not an app issue. Please report to the Ubuntu bug reports on launchpad

**Comment by Markcortbass** [comment]
Thank you! I reported this bug on launchpad: 
https://bugs.launchpad.net/media-hub/+bug/1470522

**Comment by fransschreuder** [comment]
Ok, I commented on it
