### ISSUE TITLE
next ??? in 50 meters too late

### ISSUE THREAD

**Issue by Theodin** [fransschreuder/libosmscout#25]
The message that I have to turn left  (or do something else) in 50m comes too late in my opinion. I dont know if that a libosm thing or if you can do something about it.

Thanks for your continued efforts and improvements!

**Comment by fransschreuder** [comment]
yes it can be changed, I think I have to tune it more. It is dependent on driving speed, >50km/h it should become 200m, >80km/h it should become 800 but those values should be tuned.

**Comment by fransschreuder** [comment]
how fast were you going when you thought 50m was too short? I think on a bicycle 50m is quite ok, going >30 it should become 100 or maybe even 200m. What do you think?

**Comment by Theodin** [comment]
Thats what I was going to write here even if you hadnt asked.
I was in my car, going 20-30 km/h in a residential area. On a bike, i guess the timing would be ok, but in the car, sometimes I heard the voice when I was leaving the roundabout.
Is there a possibility to indicate that I am driving by car (the routing button is set to car) and make the distance longer when routing a car and not a bike?

**Comment by Jon-of-Kent** [comment]
Hello - I'd just like to second this. When going at about 30 mph (50 km/h more or less?) the 50-metre warning is at about 10m, and the 200-metre warning is at about 50. I suspect that's what you mean with your post above? But I just thought I'd give you some more numbers... hope that's ok.

**Comment by fransschreuder** [comment]
Should be better now, please comment

**Comment by Jon-of-Kent** [comment]
Hello again - sorry it's taken me so long!  I just didn't need it for a long time.  YES - the distances seem right now, and "turn left" (or whatever) comes at an appropriate point before the turning (maybe about 10 metres or so).  Thank you.
