### ISSUE TITLE
Change location of maps to SD card

### ISSUE THREAD

**Issue by ghost** [fransschreuder/libosmscout#26]
Hi!
bq 4.5, r23, I cannot change the location to the SD card.

I have the version from Open Store, so it should work.

But when I click on the string to change the "Default download directory" absolutely nothing happens :( :(

**Comment by fransschreuder** [comment]
Ok, that's funny. Could you remove the ~/.config/osmscout.fransschreuder/\* files and try again?

**Comment by ghost** [comment]
I tried right now, then I rebooted just to be sure and nothing changes.

**Comment by fransschreuder** [comment]
could you post the contents of ~/.cache/upstart/application-click-osmscout.fransschreuder_OSMScout_0.4.6.log?

**Comment by ghost** [comment]
Sure, here it is:
http://paste.ubuntu.com/11835426/

**Comment by fransschreuder** [comment]
have you first uninstalled the normal store version? Please uninstall, then reinstall, then refresh the icons by dragging the applications scope down. It looks like apparmor is not giving you the desired rights

**Comment by ghost** [comment]
Sure I did.
Actually, it was working until when there was no choice (I have already
downloaded many maps on the SD, that I would like not to loose) :)

I will try to remove and reinstall now, then I'll let you know.

**Comment by ghost** [comment]
Ok great, now it works! :)

But there is another problem, i.e. it only sees one installed map
(ile_de_france) while many others are already there, downloaded through the
previous version.

Some hint on how to make it recognize them?

**Comment by fransschreuder** [comment]
There seem to be more problems, it also can't get access to the mp3 files in the application directory

**Comment by fransschreuder** [comment]
if you take a file browser, are the files ile_de_france in the same folder as the others? or is ile_de_france in ~/.local/share/osmscout.fransschreuder

**Comment by ghost** [comment]
They are with the others.
In that folder there is only an empty "Maps" folder.

**Comment by kyokenn** [comment]
I can't change a location to SD card too. The only available option is home directory which is located in internal flash memory. Symbolic links from application directory to SD card does not working too.

**Comment by fransschreuder** [comment]
Do you have the version from the open store?
If you have downloaded it from the Ubuntu Store, it's a known "feature" of the os.

**Comment by kyokenn** [comment]
I have the version from Ubuntu Store. What is the open store?

**Comment by fransschreuder** [comment]
Ok, so that's the problem. Apps in the Ubuntu store are not allowed to have SD card access, for some funny security reasons nobody understands. 
Also another important feature of a routing app is not allowed in the Ubuntu store, that is to keep the screen on while the app is focused.
Both features are available in the version that can be found in the open store:
https://open.uappexplorer.com/

**Comment by kyokenn** [comment]
Thanks! It works that way. I think we need apparmor profiles like "networking" for RW access to SD card.

**Comment by fransschreuder** [comment]
Yes, I have sent a million messages to ubuntu people, they are thinking about a solution but things are advancing too slow to my taste
