### ISSUE TITLE
Warning about the Ubuntu-Phone Bug

### ISSUE THREAD

**Issue by jv-barsuk** [fransschreuder/libosmscout#28]
This is just a suggestion: Ubuntu-Phone has a bug when using Wifi and GPS in combination (see this bug https://bugs.launchpad.net/oxide/+bug/1462664). The first thing I did, was to blame the app. If you would give some information about this bug when launching the app, it might be less frustrating for some people. That would just be necessary till the bug is fixed.

**Comment by fransschreuder** [comment]
I think it's better since OTA5
