### ISSUE TITLE
Support OCM maps

### ISSUE THREAD

**Issue by jv-barsuk** [fransschreuder/libosmscout#30]
Support Open Cycle Maps in the download area.

**Comment by fransschreuder** [comment]
If you have means to download osm or pbf files for that...
plus I need extra space :(

**Comment by jv-barsuk** [comment]
Just had a look in this and after a discussion on the OSM IRC I'm now certain about that we can't easily get the ocm data because the style seems to be closed source. I contacted Andy from http://thunderforest.com if we could find any solution for that.
