### ISSUE TITLE
Add screen on + landscape mode

### ISSUE THREAD

**Issue by ktatar156** [fransschreuder/libosmscout#33]
Hello,
is that project still in active development? I think that's a great app! Could you add avoiding to turn screen off and landscape mode (from OTA-5 both are technically available)?

**Comment by fransschreuder** [comment]
Hello,

Landscape mode should work from OTA-5. Doesn't it for you?
Also avoid screen off is implemented if you take the version from open-store. I am developing this app on my own and am still planning to invest time, however it's a big project to do on my own. Help will be appreciated.

Frans

**Comment by ktatar156** [comment]
It works, but on MX4 didn't look pretty good (some blank spaces on one side). But I've restarted phone and now is good! :) Can't help you for now in coding (I know only a little VBA, R). Did you consider to use crowdfunding and get resources to hire someone or other stuff (I don't know what else that project need)? I think Ubuntu community is really good and you could get some support in that way (your project is the first offline navi for Ubuntu and God now that we all need it! :) )
Some suggestion: usually when I drive highway I turn off my screen in Android Google Maps. When there will be need to turn somewhere, screen is turning on (and some voice what to do). That's a great feature to save battery life for long trips!
