### ISSUE TITLE
Keep screen on

### ISSUE THREAD

**Issue by Markcortbass** [fransschreuder/libosmscout#34]
The display turns off while using the app. The application uNav (GPS Navigation), doesn't have this issue. 
Could you add this very functional solution to your app?
Unav: http://bazaar.launchpad.net/~unav-devs/unav/trunk/files

It was this bug:
https://bugs.launchpad.net/ubuntu/+source/unity8/+bug/1462489

Solution:
"For the developer documentation changes to https://developer.ubuntu.com/en/start/platform/guides/app-confinement/:
1. add 'keep-display-on' to the 'Policy groups' section (ie, the output of 'aa-easyprof --policy-vendor=ubuntu --policy-version=1.3 --list-policy-groups')
2. under Usage/common, add:
  keep-display-on: Can request keeping the screen on

```
QML: qtdeclarative5-systeminfo-plugin
import QtSystemInfo <version>"
```

**Comment by Markcortbass** [comment]
This is the solution:

File "OSMScout.apparmor"

{
    "policy_groups": [
        "location",
        "networking",
        "audio",
    "keep-screen-on"
    ],
    "policy_version": 1.3
}

File: "main.qml"

import QtQuick 2.3
import Ubuntu.Components 1.1
import Ubuntu.Components.Popups 1.0

//import QtQuick.Controls 1.2
import QtQuick.Layouts 1.1
//import QtQuick.Controls.Styles 1.2
import QtQuick.Window 2.0

import QtPositioning 5.3
import QtSystemInfo 5.0
import QtMultimedia 5.0
import net.sf.libosmscout.map 1.0
import Qt.labs.settings 1.0

import "custom"
Window{
    //Avoid screen from going blank after some time...
    ScreenSaver {
        id: screenSaver
    screenSaverEnabled: !Qt.application.active
    }

**Comment by fransschreuder** [comment]
uploaded since 0.5.2
