### ISSUE TITLE
map update

### ISSUE THREAD

**Issue by ombriano** [fransschreuder/libosmscout#44]
After the command:
sudo apt-get install libosmscoutimportgui0

E: Could not find package libosmscoutimportgui0

**Comment by Theodin** [comment]
Did you add the PPA (sudo apt-add-reporitory ppa:fransschreuder1/osmscout-import) first?

**Comment by ombriano** [comment]
Yes i did it.

----Messaggio originale----

Da: Theodin notifications@github.com

Data: 28/02/2016 9.34

A: "fransschreuder/OSMScout-ubuntu"OSMScout-ubuntu@noreply.github.com

Cc: "ombriano"fage.testa_b@libero.it

Ogg: Re: [OSMScout-ubuntu] map update (#44)

Did you add the PPA (sudo apt-add-reporitory ppa:fransschreuder1/osmscout-import) first?

**Comment by ghost** [comment]
Looking at https://launchpad.net/~fransschreuder1/+archive/ubuntu/osmscout-import/+packages, it looks like the package is named `osmscoutimportgui0`, without the "lib".

**Comment by ombriano** [comment]
I tried without "lib" is what happens

The repository 'http://ppa.launchpad.net/fransschreuder1/osmscout-import/ubuntu xenial Release' does not have a Release file.Data from such a repository can't be authenticated and is therefore potentially dangerous to use.See apt-secure(8) manpage for repository creation and user configuration details.Failed to fetch http://ppa.launchpad.net/fransschreuder1/osmscout-import/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not FoundFailed to fetch http://ppa.launchpad.net/fransschreuder1/osmscout-import/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not FoundImpossibile scaricare alcuni file di indice: saranno ignorati o
 verranno usati quelli vecchi
