### ISSUE TITLE
Version 0.3.4 crashes when zooming in

### ISSUE THREAD

**Issue by Sturmflut** [fransschreuder/libosmscout#5]
Device: Meizu MX4 Ubuntu Edition
channel: ubuntu-touch/stable/meizu.en
version version: 1
version ubuntu: 20150602
version device: 20150522-a851049
version custom: 20150602-731-5-32

I've installed version 0.3.4 from the store and downloaded the "slovakia" map using the built-in wizard. When I try to zoom in, the app always crashes when the zoom level goes above a certain value (I can't tell which one exactly, since there is no zoom level indicator).

These are the last lines in the log file before a crash:

Draw: [-19,84113 S -12,15000 W - 19,84113 N 12,15000 E] 64x/6 1152x1920 100.00000 DPI
UbuntuClipboard - Got invalid serialized mime data. Ignoring it.
All: 0.288 Data: 0.015 Draw: 0.272

Draw: [29,18149 N 3,80614 E - 62,85824 N 35,85176 E] 32x/5 1152x1830 100.00000 DPI
Paths: 0/0/0/0 (pcs) 0.000/0.000/0.000 (sec)
Areas: 0/0/0 (pcs) 0.000/0.000/0.000 (sec)
Nodes: 0+0/0 (pcs) 0.000/0.000 (sec)
Labels: 0/0/0 (pcs) 0.000 (sec)
All: 0.110 Data: 0.010 Draw: 0.100
Quick zooming
qml: Pinch started
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming

Draw: [44,67522 N 16,08742 E - 52,51512 N 23,57048 E] 137x/7 1152x1830 100.00000 DPI
Paths: 189/189/189/0 (pcs) 0.003/0.019/0.000 (sec)
Areas: 497/498/498 (pcs) 0.014/0.028/0.002 (sec)
Nodes: 3+0/3 (pcs) 0.000/0.000 (sec)
Labels: 0/0/0 (pcs) 0.000 (sec)
All: 0.162 Data: 0.017 Draw: 0.145

Draw: [44,67522 N 16,08742 E - 52,51512 N 23,57048 E] 137x/7 1152x1830 100.00000 DPI
Paths: 189/189/189/0 (pcs) 0.002/0.008/0.000 (sec)
Areas: 497/498/498 (pcs) 0.011/0.013/0.000 (sec)
Nodes: 3+0/3 (pcs) 0.003/0.000 (sec)
Labels: 3/0/3 (pcs) 0.003 (sec)
All: 0.098 Data: 0.018 Draw: 0.080
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming

Draw: [44,16031 N 13,95177 E - 52,13834 N 21,50056 E] 137x/7 1152x1830 100.00000 DPI
All: 0.111 Data: 0.020 Draw: 0.090

Draw: [44,16031 N 13,95177 E - 52,13834 N 21,50056 E] 137x/7 1152x1830 100.00000 DPI
Paths: 189/168/168/0 (pcs) 0.002/0.016/0.000 (sec)
Areas: 497/457/457 (pcs) 0.010/0.024/0.001 (sec)
Nodes: 3+0/3 (pcs) 0.000/0.000 (sec)
Labels: 3/0/3 (pcs) 0.006 (sec)
All: 0.155 Data: 0.012 Draw: 0.142
Quick zooming
qml: Pinch started
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming
Quick zooming

File open...
HasError: false
Opening WayDataFile: 0.000
OSMScout: ../../OSMScout/libosmscout/include/osmscout/TypeConfig.h:1121: const TypeInfoRef osmscout::TypeConfig::GetWayTypeInfo(osmscout::TypeId) const: Assertion `id<=wayTypes.size()' failed.

**Comment by fransschreuder** [comment]
Thanks for the report. I will make a check on the zoomlevel.

**Comment by fransschreuder** [comment]
Could it be that your map is corrupted? I have tried with Slovakia and it doesn't crash.
If you upgrade your OSMScout to 0.3.7, and redownload the map, it will check the md5sum of the map files.

**Comment by fransschreuder** [comment]
Since I got no reply I guess it's alright. If the problem persists, please reopen the issue
