### ISSUE TITLE
Table "GUESTBOOK" not found

### ISSUE THREAD

**Issue by ILoveHubGit** [fransschreuder/libosmscout#53]
I'm trying to get the clojure application "guestbook" working. But when I run the application and browse to it at localhost:3000 I get an error:

org.h2.jdbc.JdbcSQLException at /
Table "GUESTBOOK" not found; SQL statement:
SELECT \* FROM guestbook [42102-192]

I think something during "lein run migrate" is not working. The output I get from this is:

read config from resource: "config.edn"
read config from file: ".lein-env"
2016-09-12 21:34:43,273 [main] INFO  migratus.core - Starting migrations 
2016-09-12 21:34:43,328 [main] INFO  migratus.database - creating migration table 'schema_migrations' 
2016-09-12 21:34:43,348 [main] INFO  migratus.core - Ending migrations 

I thought I've seen somewhere that it should give information about the tables as well, but I can't find it anymore

Please help

**Comment by fransschreuder** [comment]
I think you are commenting on the wrong project

**Comment by ILoveHubGit** [comment]
Sorry. I'll move it to another
