### ISSUE TITLE
md5sum of routebicycle.dat failed (map of Spain)

### ISSUE THREAD

**Issue by advocatux** [fransschreuder/libosmscout#54]
I'm trying to download the map of Spain and the downloading fails with this error `md5sum of routebicycle.dat failed`

I've downloaded manually that file from http://schreuderelectronics.com/osm/spain/ and I see the md5sum differs from the one in http://schreuderelectronics.com/osm/spain/md5sums (`d41d8cd98f00b204e9800998ecf8427e` for the former vs `99c9c672c120817d1761aa1fcb9102ab` for the latter).

Thank you for your work !!

**Comment by fransschreuder** [comment]
Alright, let me have a look. I confirm and rebuild Spain.

**Comment by fransschreuder** [comment]
I just regenerated spain. Please retry and close if it is working

**Comment by Gorsh2** [comment]
Hi Frans. I can confirm the same behaviour with Argentina map.

**Comment by advocatux** [comment]
It works now. 

Thanks again for your work !!

**Comment by fransschreuder** [comment]
Hello @Gorsh2, I downloaded Argentina and it works fine. No problem there, please retry

**Comment by Gorsh2** [comment]
Sorry to insist, but I retried and it's still the same.
![screenshot20180902_000957960](https://user-images.githubusercontent.com/12127781/44951873-de943a00-ae46-11e8-8795-440e57ecbaf0.png)

**Comment by fransschreuder** [comment]
It can happen if you have a crappy connection, but the map is fine

**Comment by CesarHerreraG** [comment]
Could I generate the map of Spain from OpenStreetMap?
