### ISSUE TITLE
Rotate the map in driving direction

### ISSUE THREAD

**Issue by fransschreuder** [fransschreuder/libosmscout#8]

**Comment by Theodin** [comment]
I second that feature request. Was one of the things I was missing today :)

**Comment by fransschreuder** [comment]
Done, download 0.3.8 from the store!

**Comment by Theodin** [comment]
Wow you're quick! Thats the third update today, isnt it? :)

**Comment by fransschreuder** [comment]
Yes it is, and also 3 yesterday :P
